import type { Product } from "../types/Product";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Mechanical Keyboard",
    description: "Hot-swappable RGB mechanical keyboard.",
    price: 129.99,
    categoryId: 1,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "Keychron",
    rating: 4.8,
    sku: "KEY-001",
    stockQuantity: 12,
  },
  {
    id: 2,
    name: "Wireless Mouse",
    description: "Ergonomic low-latency wireless mouse.",
    price: 59.99,
    categoryId: 1,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "Logitech",
    rating: 4.6,
    sku: "MOU-002",
    stockQuantity: 30,
  },
  {
    id: 3,
    name: "27-inch Monitor",
    description: "1440p IPS display with 144Hz refresh.",
    price: 299.99,
    categoryId: 2,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "Dell",
    rating: 4.7,
    sku: "MON-003",
    stockQuantity: 8,
  },
  {
    id: 4,
    name: "Gaming Headset",
    description: "Surround sound headset with detachable mic.",
    price: 89.99,
    categoryId: 3,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "SteelSeries",
    rating: 4.5,
    sku: "AUD-004",
    stockQuantity: 20,
  },
  {
    id: 5,
    name: "Laptop Stand",
    description: "Aluminum adjustable stand.",
    price: 39.99,
    categoryId: 4,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "Rain Design",
    rating: 4.4,
    sku: "ACC-005",
    stockQuantity: 50,
  },
  {
    id: 6,
    name: "USB-C Dock",
    description: "Dual monitor docking station.",
    price: 149.99,
    categoryId: 4,
    imageUrl: "Images/SharkRocket.png",
    manufacturuer: "Anker",
    rating: 4.7,
    sku: "DOC-006",
    stockQuantity: 15,
  }
];